// Fetch Messages
export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";

// Send Message
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

// Fetch Chat By Project
export const FETCH_CHAT_BY_PROJECT_REQUEST = "FETCH_CHAT_BY_PROJECT_REQUEST";
export const FETCH_CHAT_BY_PROJECT_SUCCESS = "FETCH_CHAT_BY_PROJECT_SUCCESS";
export const FETCH_CHAT_BY_PROJECT_FAILURE = "FETCH_CHAT_BY_PROJECT_FAILURE";

// Fetch Chat Messages
export const FETCH_CHAT_MESSAGES_REQUEST = "FETCH_CHAT_MESSAGES_REQUEST";
export const FETCH_CHAT_MESSAGES_SUCCESS = "FETCH_CHAT_MESSAGES_SUCCESS";
export const FETCH_CHAT_MESSAGES_FAILURE = "FETCH_CHAT_MESSAGES_FAILURE";
